#!/usr/bin/env python3
"""Translate .pyih stub sources to .pyi stub files.

.pyih files use two custom constructs that this script expands:

1. XFunc[[A], B] — Extended function semantics (mapper mode)
   Expands to 7 @overload variants (Callable, None, Set, Regex, int, slice, Mapping)

2. XPred[A] — Extended function semantics (predicate mode)
   Expands to 7 @overload variants that preserve the element type

3. [C: (list, set, ...)] — Collection type expansion
   Substitutes C with each concrete type listed in the bound

Functions without these constructs pass through unchanged.
Non-XFunc overloads of the same function pass through unchanged.
A `# xfunc_skip: variant1, variant2` comment before a function skips those variants.

Requires Python 3.12+ (for PEP 695 type param parsing). Generated .pyi files work on any Python.
"""
import ast
import re
from pathlib import Path

FUNCY_DIR = Path(__file__).parent / "funcy"

# Header for generated files
GENERATED_HEADER = "# THIS FILE IS AUTOGENERATED by translate_pyih.py from {source}. DO NOT EDIT.\n"


def find_pyih_files():
    """Find all .pyih files in funcy/."""
    return sorted(FUNCY_DIR.glob("*.pyih"))


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

_XFUNC_SKIP_RE = re.compile(r'\s*#\s*xfunc_skip:\s*(.+)')


def extract_xfunc_skip(lines: list[str]) -> tuple[set[str], list[str]]:
    """Extract xfunc_skip directives from a list of source lines.

    Returns (skip_set, remaining_lines) where skip_set contains the variant names
    to skip and remaining_lines are the lines without the xfunc_skip directives.
    """
    skip = set()
    remaining = []
    for line in lines:
        m = _XFUNC_SKIP_RE.match(line)
        if m:
            skip = {s.strip() for s in m.group(1).split(',')}
        else:
            remaining.append(line)
    return skip, remaining


def parse_pyih(source: str) -> list[dict]:
    """Parse a .pyih file into a list of items (imports, comments, functions, etc.).

    Returns a list of dicts, each with:
      - kind: 'verbatim' | 'func_group'
      - For 'verbatim': text (str)
      - For 'func_group': name (str), overloads (list of overload dicts)
        Each overload dict has:
          - name: function name (str)
          - params: list of (name, annotation_str)
          - return_type: str
          - xfunc_param: name of param with XFunc/XPred annotation, or None
          - xfunc_kind: 'XFunc' | 'XPred' | None
          - xfunc_a: type var name for A, or None
          - xfunc_b: type var name for B, or None (XFunc only)
          - coll_var: name of collection type var C, or None
          - coll_types: list of concrete types for C, or None
          - xfunc_skip: set of variant names to skip
    """
    tree = ast.parse(source)
    source_lines = source.splitlines()

    items = []
    last_end = 0  # 0-indexed exclusive end of last consumed line

    body = tree.body
    i = 0

    while i < len(body):
        node = body[i]

        if not isinstance(node, ast.FunctionDef):
            # Non-function node: verbatim from last_end through end of this node
            lines = source_lines[last_end:node.end_lineno]
            if lines:
                items.append({'kind': 'verbatim', 'text': '\n'.join(lines)})
            last_end = node.end_lineno
            i += 1
            continue

        func_name = node.name
        func_start = node.lineno - 1  # 0-indexed

        # Lines between last_end and this function's start may contain:
        # - regular verbatim content (comments, blanks)
        # - xfunc_skip directive applying to the first overload
        pre_lines = source_lines[last_end:func_start]
        xfunc_skip_first, clean_pre = extract_xfunc_skip(pre_lines)
        if clean_pre:
            items.append({'kind': 'verbatim', 'text': '\n'.join(clean_pre)})

        # Collect all consecutive same-name FunctionDef overloads
        overloads = []
        xfunc_skip = xfunc_skip_first

        while i < len(body) and isinstance(body[i], ast.FunctionDef) and body[i].name == func_name:
            func_node = body[i]
            overloads.append(parse_func_node(func_node, xfunc_skip))
            last_end = func_node.end_lineno
            xfunc_skip = set()

            # Look ahead: if next node is same-name FunctionDef, scan the gap
            # between this overload's end and next overload's start for xfunc_skip
            if (i + 1 < len(body)
                    and isinstance(body[i + 1], ast.FunctionDef)
                    and body[i + 1].name == func_name):
                next_start = body[i + 1].lineno - 1
                gap_lines = source_lines[func_node.end_lineno:next_start]
                xfunc_skip, _ = extract_xfunc_skip(gap_lines)

            i += 1

        items.append({'kind': 'func_group', 'name': func_name, 'overloads': overloads})

    # Trailing content after all body nodes
    trailing = source_lines[last_end:]
    if trailing and '\n'.join(trailing).strip():
        items.append({'kind': 'verbatim', 'text': '\n'.join(trailing)})

    return items


def annotation_to_str(node: ast.expr) -> str:
    """Convert an AST annotation node back to its source string."""
    return ast.unparse(node)


def parse_func_node(node: ast.FunctionDef, xfunc_skip: set) -> dict:
    """Parse an ast.FunctionDef into an overload dict."""
    # Collection type params: def f[C: (list, set)]()
    coll_var = None
    coll_types = None
    for tp in node.type_params:
        if isinstance(tp, ast.TypeVar) and tp.bound is not None and isinstance(tp.bound, ast.Tuple):
            coll_var = tp.name
            coll_types = [annotation_to_str(e) for e in tp.bound.elts]
            break

    # Build params list, including defaults as part of the type string ("type = default")
    args = node.args
    all_args = args.args
    n_defaults = len(args.defaults)
    default_offset = len(all_args) - n_defaults

    # FIX: this function looks weird, like we undo the parsing to convert back to string,
    #      should not do that, should work with structured data
    # RES: All three string-vs-structured-data FIXes (here, XFunc regex detection at ~L207,
    #      and replace_typevar_in_container at ~L358) are coupled. The early stringification
    #      here forces regex use downstream. Proper fix: store ast.expr nodes in params (with
    #      defaults as a separate field), detect XFunc/XPred by checking isinstance(node,
    #      ast.Subscript) with node.value.id == 'XFunc'/'XPred', and substitute typevars via
    #      an AST transformer. Stringify only at final output. This touches ~15 functions across
    #      the whole pipeline — too large/risky for a single pass. Do it as a dedicated branch
    #      with incremental steps: (1) add ast.expr to param tuples alongside strings,
    #      (2) switch XFunc/XPred detection to AST, (3) switch substitutions to AST transforms,
    #      (4) remove string intermediaries. Verify output unchanged after each step.
    params = []
    for j, arg in enumerate(all_args):
        pname = arg.arg
        ptype = annotation_to_str(arg.annotation) if arg.annotation else ''
        if j >= default_offset:
            default_str = annotation_to_str(args.defaults[j - default_offset])
            ptype = f'{ptype} = {default_str}' if ptype else f'= {default_str}'
        params.append((pname, ptype))

    # *args (vararg)
    if args.vararg:
        va = args.vararg
        ptype = annotation_to_str(va.annotation) if va.annotation else ''
        params.append((f'*{va.arg}', ptype))

    # keyword-only args
    for j, arg in enumerate(args.kwonlyargs):
        pname = arg.arg
        ptype = annotation_to_str(arg.annotation) if arg.annotation else ''
        kw_default = args.kw_defaults[j]
        if kw_default is not None:
            default_str = annotation_to_str(kw_default)
            ptype = f'{ptype} = {default_str}' if ptype else f'= {default_str}'
        params.append((pname, ptype))

    # **kwargs
    if args.kwarg:
        kw = args.kwarg
        ptype = annotation_to_str(kw.annotation) if kw.annotation else ''
        params.append((f'**{kw.arg}', ptype))

    return_type = annotation_to_str(node.returns) if node.returns else ''

    # Detect XFunc/XPred in params (regex on unparsed annotation strings)
    xfunc_param = None
    xfunc_kind = None
    xfunc_a = None
    xfunc_b = None
    for pname, ptype in params:
        # Strip default from ptype for matching
        base_type = ptype.split(' = ')[0]
        # FIX: on top of the above, this looks like remnant of regex parsing
        # RES: Coupled with FIX at ~L164. Once params store ast.expr nodes, detect XFunc/XPred
        #      via isinstance(annotation, ast.Subscript) and annotation.value.id check.
        xf_match = re.match(r'XFunc\[\[(\w+)\],\s*(\w+)\]', base_type)
        if xf_match:
            xfunc_param = pname
            xfunc_kind = 'XFunc'
            xfunc_a = xf_match.group(1)
            xfunc_b = xf_match.group(2)
            break
        xp_match = re.match(r'XPred\[(\w+)\]', base_type)
        if xp_match:
            xfunc_param = pname
            xfunc_kind = 'XPred'
            xfunc_a = xp_match.group(1)
            break

    return {
        'name': node.name,
        'params': params,
        'return_type': return_type,
        'xfunc_param': xfunc_param,
        'xfunc_kind': xfunc_kind,
        'xfunc_a': xfunc_a,
        'xfunc_b': xfunc_b,
        'coll_var': coll_var,
        'coll_types': coll_types,
        'xfunc_skip': xfunc_skip,
    }


# ---------------------------------------------------------------------------
# XFunc / XPred Expansion
# ---------------------------------------------------------------------------

# Standard type var names used in generated output
TYPEVARS = {'_T', '_V', '_K', '_K2', '_V2', '_T2'}

# The 7 XFunc variants
XFUNC_VARIANTS = [
    'Callable', 'None', 'Set', 'Regex', 'int', 'slice', 'Mapping',
]


def expand_xfunc(overload: dict) -> list[str]:
    """Expand an XFunc overload into 7 variant overloads."""
    a_var = overload['xfunc_a']
    b_var = overload['xfunc_b']
    skip = overload['xfunc_skip']
    results = []

    for variant in XFUNC_VARIANTS:
        if variant.lower() in {s.lower() for s in skip}:
            continue
        lines = generate_xfunc_variant(overload, variant, a_var, b_var)
        if lines:
            results.extend(lines)

    return results


def generate_xfunc_variant(overload: dict, variant: str, a_var: str, b_var: str) -> list[str]:
    """Generate a single XFunc variant overload."""
    params = overload['params']
    return_type = overload['return_type']
    func_param = overload['xfunc_param']

    # Build new params list with the XFunc param replaced
    new_params = []
    for pname, ptype in params:
        if pname == func_param:
            new_ptype = get_xfunc_param_type(variant, a_var, b_var)
            new_params.append((pname, new_ptype))
        else:
            new_ptype = substitute_xfunc_type(ptype, variant, a_var, b_var, is_input=True)
            new_params.append((pname, new_ptype))

    new_return = substitute_xfunc_type(return_type, variant, a_var, b_var, is_input=False)

    func_name = overload['name']
    params_str = ', '.join(f'{n}: {t}' if t else n for n, t in new_params)

    return [
        '@overload',
        f'def {func_name}({params_str}) -> {new_return}: ...',
    ]


def get_xfunc_param_type(variant: str, a_var: str, b_var: str) -> str:
    """Get the type annotation for the XFunc param in the given variant."""
    match variant:
        case 'Callable':
            return f'Callable[[{a_var}], {b_var}]'
        case 'None':
            return 'None'
        case 'Set':
            return f'AbstractSet[{a_var}]'
        case 'Regex':
            return 'str | bytes | re.Pattern[str]'
        case 'int':
            return 'int'
        case 'slice':
            return 'slice'
        case 'Mapping':
            return f'Mapping[{a_var}, {b_var}]'
    raise ValueError(f"Unknown variant: {variant}")


def substitute_xfunc_type(type_str: str, variant: str, a_var: str, b_var: str | None,
                          is_input: bool) -> str:
    """Substitute A/B type vars in a type string for the given XFunc variant."""
    s = type_str
    match variant:
        case 'Callable':
            # A and B stay as type vars — no change needed
            pass
        case 'None':
            # B becomes A (identity)
            if b_var:
                s = replace_typevar_in_container(s, b_var, a_var)
        case 'Set':
            # B becomes bool, A stays (but Set takes Any for the set itself)
            if b_var:
                s = replace_typevar_in_container(s, b_var, 'bool')
            # For input types containing Iterable[A], we keep A since Set[A] constrains membership
        case 'Regex':
            # B becomes _ReResult | None, A becomes Any (regex erases input type info)
            if b_var:
                s = replace_typevar_in_container(s, b_var, '_ReResult | None')
            s = replace_typevar_in_container(s, a_var, 'Any')
        case 'int':
            # For inputs and outputs: A becomes Sequence[_T], B becomes _T
            s = replace_typevar_in_container(s, a_var, 'Sequence[_T]')
            if b_var:
                s = replace_typevar_in_container(s, b_var, '_T')
        case 'slice':
            # A becomes Sequence[_T], B becomes Sequence[_T]
            s = replace_typevar_in_container(s, a_var, 'Sequence[_T]')
            if b_var:
                s = replace_typevar_in_container(s, b_var, 'Sequence[_T]')
        case 'Mapping':
            # A and B are used as Mapping[A, B] key/value — they stay as type vars
            pass
    return s


def replace_typevar_in_container(type_str: str, var: str, replacement: str) -> str:
    """Replace a type var when it appears as a type parameter in a container.

    E.g., Iterable[A] -> Iterable[Sequence[_T]] but not standalone A.
    """
    # Replace A when it appears inside brackets: [..., A, ...] or [A]
    # Use word boundary to avoid partial matches
    # FIX: will this be easier if we don't keep strings and work with ast nodes OR other way
    #      structured data?
    # RES: Yes. With AST nodes, this becomes an ast.NodeTransformer that replaces Name(id=var)
    #      nodes with the replacement subtree. Coupled with FIX at ~L164 — see plan there.
    return re.sub(r'\b' + re.escape(var) + r'\b', replacement, type_str)


# ---------------------------------------------------------------------------
# XPred Expansion
# ---------------------------------------------------------------------------

def expand_xpred(overload: dict) -> list[str]:
    """Expand an XPred overload into 7 variant overloads."""
    a_var = overload['xfunc_a']
    skip = overload['xfunc_skip']
    results = []

    for variant in XFUNC_VARIANTS:
        if variant.lower() in {s.lower() for s in skip}:
            continue
        lines = generate_xpred_variant(overload, variant, a_var)
        if lines:
            results.extend(lines)

    return results


def generate_xpred_variant(overload: dict, variant: str, a_var: str) -> list[str]:
    """Generate a single XPred variant overload."""
    params = overload['params']
    return_type = overload['return_type']
    func_param = overload['xfunc_param']

    new_params = []
    for pname, ptype in params:
        if pname == func_param:
            new_ptype = get_xpred_param_type(variant, a_var)
            new_params.append((pname, new_ptype))
        else:
            new_ptype = substitute_xpred_type(ptype, variant, a_var)
            new_params.append((pname, new_ptype))

    new_return = substitute_xpred_type(return_type, variant, a_var)

    func_name = overload['name']
    params_str = ', '.join(f'{n}: {t}' if t else n for n, t in new_params)

    return [
        '@overload',
        f'def {func_name}({params_str}) -> {new_return}: ...',
    ]


def get_xpred_param_type(variant: str, a_var: str) -> str:
    """Get the pred type annotation for the given variant."""
    match variant:
        case 'Callable':
            return f'Callable[[{a_var}], Any]'
        case 'None':
            return 'None'
        case 'Set':
            return f'AbstractSet[{a_var}]'
        case 'Regex':
            return 'str | bytes | re.Pattern[str]'
        case 'int':
            return 'int'
        case 'slice':
            return 'slice'
        case 'Mapping':
            return f'Mapping[{a_var}, Any]'
    raise ValueError(f"Unknown variant: {variant}")


def substitute_xpred_type(type_str: str, variant: str, a_var: str) -> str:
    """Substitute A type var in type strings for XPred variants.

    For predicates, the element type is preserved but the input constraint changes.
    """
    s = type_str
    match variant:
        case 'Callable' | 'None':
            pass  # A stays as-is
        case 'Set' | 'Mapping':
            pass  # A stays — Set[A]/Mapping[A, Any] constrains against Iterable[A]
        case 'Regex':
            # Regex only works on strings
            s = re.sub(r'\b' + re.escape(a_var) + r'\b', 'str', s)
        case 'int':
            # int indexes into sequences: constrain A to Sequence[Any]
            s = re.sub(r'\b' + re.escape(a_var) + r'\b', 'Sequence[Any]', s)
        case 'slice':
            s = re.sub(r'\b' + re.escape(a_var) + r'\b', 'Sequence[Any]', s)
    return s


# ---------------------------------------------------------------------------
# Collection Type Expansion
# ---------------------------------------------------------------------------

# Mapping-like types that take 2 type params
TWO_PARAM_TYPES = {'dict', 'Mapping', 'defaultdict', 'OrderedDict', 'Counter'}


def expand_collection_types(overload: dict) -> list[dict]:
    """Expand a collection-parameterized overload into one per concrete type."""
    coll_var = overload['coll_var']
    coll_types = overload['coll_types']

    results = []
    for ctype in coll_types:
        new_overload = overload.copy()
        new_overload['coll_var'] = None
        new_overload['coll_types'] = None

        # Substitute C with the concrete type in params and return type
        new_params = []
        for pname, ptype in overload['params']:
            new_ptype = substitute_coll_type(ptype, coll_var, ctype)
            new_params.append((pname, new_ptype))
        new_overload['params'] = new_params
        new_overload['return_type'] = substitute_coll_type(
            overload['return_type'], coll_var, ctype)

        results.append(new_overload)
    return results


def substitute_coll_type(type_str: str, coll_var: str, ctype: str) -> str:
    """Replace C[X] or C[X, Y] with concrete_type[X] or concrete_type[X, Y]."""
    return re.sub(r'\b' + re.escape(coll_var) + r'\b', ctype, type_str)


# ---------------------------------------------------------------------------
# Output Generation
# ---------------------------------------------------------------------------

def generate_overload_lines(overload: dict) -> list[str]:
    """Generate output lines for a single overload (after expansion)."""
    func_name = overload['name']
    params_str = ', '.join(f'{n}: {t}' if t else n for n, t in overload['params'])
    return [f'def {func_name}({params_str}) -> {overload["return_type"]}: ...']


def generate_func_group(group: dict) -> str:
    """Generate output for a function group (all overloads of same name)."""
    all_lines = []

    for overload in group['overloads']:
        has_xfunc = overload['xfunc_kind'] is not None
        has_coll = overload['coll_var'] is not None

        if has_coll and has_xfunc:
            # Expand collection types first, then XFunc/XPred within each
            for coll_overload in expand_collection_types(overload):
                if coll_overload['xfunc_kind'] == 'XFunc':
                    all_lines.extend(expand_xfunc(coll_overload))
                else:
                    all_lines.extend(expand_xpred(coll_overload))
        elif has_coll:
            # Collection expansion only
            for coll_overload in expand_collection_types(overload):
                all_lines.append('@overload')
                all_lines.extend(generate_overload_lines(coll_overload))
        elif has_xfunc:
            if overload['xfunc_kind'] == 'XFunc':
                all_lines.extend(expand_xfunc(overload))
            else:
                all_lines.extend(expand_xpred(overload))
        else:
            # Pass through as-is
            all_lines.extend(generate_overload_lines(overload))

    # Count actual function defs (non-decorator lines)
    func_lines = [line for line in all_lines if line.startswith('def ')]
    needs_overload = len(func_lines) > 1

    if needs_overload:
        # Add @overload before each def that doesn't already have one
        result_lines = []
        for line in all_lines:
            if line.startswith('def '):
                # Check if previous line is already @overload
                if not result_lines or result_lines[-1] != '@overload':
                    result_lines.append('@overload')
            result_lines.append(line)
        return '\n'.join(result_lines)
    else:
        # Single def, no @overload needed — strip any existing @overload
        return '\n'.join(line for line in all_lines if line != '@overload')


def generate_pyi(source: str, source_name: str) -> str:
    """Generate .pyi content from .pyih source."""
    items = parse_pyih(source)
    output_parts = [GENERATED_HEADER.format(source=source_name)]

    for item in items:
        if item['kind'] == 'verbatim':
            output_parts.append(item['text'])
        elif item['kind'] == 'func_group':
            output_parts.append(generate_func_group(item))

    result = '\n'.join(output_parts)

    # Clean up: remove excessive blank lines (3+ -> 2), ensure trailing newline
    result = re.sub(r'\n{3,}', '\n\n', result)
    if not result.endswith('\n'):
        result += '\n'

    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    pyih_files = find_pyih_files()
    if not pyih_files:
        print("No .pyih files found in funcy/")
        return

    for pyih_path in pyih_files:
        pyi_path = pyih_path.with_suffix('.pyi')
        source_name = pyih_path.name

        print(f"Generating {pyi_path.name} from {source_name}...")
        source = pyih_path.read_text()
        output = generate_pyi(source, source_name)
        pyi_path.write_text(output)
        print(f"  -> {pyi_path}")

    print("Done.")


if __name__ == '__main__':
    main()
