import re
from collections.abc import Callable, Iterable, Iterator, Mapping, Set as AbstractSet, Sequence
from typing import Any, TypeAlias, TypeVar, overload

__all__ = ['empty', 'iteritems', 'itervalues',
           'join', 'merge', 'join_with', 'merge_with',
           'walk', 'walk_keys', 'walk_values', 'select', 'select_keys', 'select_values',
           'split_keys', 'compact',
           'is_distinct', 'all', 'any', 'none', 'one', 'some',
           'zipdict', 'flip', 'project', 'omit', 'zip_values', 'zip_dicts',
           'where', 'pluck', 'pluck_attr', 'invoke', 'lwhere', 'lpluck', 'lpluck_attr', 'linvoke',
           'get_in', 'get_lax', 'set_in', 'update_in', 'del_in', 'has_path']

_K = TypeVar('_K')
_K2 = TypeVar('_K2')
_V = TypeVar('_V')
_V2 = TypeVar('_V2')
_T = TypeVar('_T')

# Non-callable types accepted by the extended function protocol (funcmakers.make_func):
# int/slice for itemgetter, str/bytes/re.Pattern for regex,
# Mapping for lookup, Set for membership, None for identity/bool
_Func = int | slice | str | bytes | re.Pattern[str] | Mapping[Any, Any] | AbstractSet[Any] | None
_ReResult: TypeAlias = str | tuple[str, ...] | dict[str, str]

### Generic ops

def empty(coll: _T) -> _T: ...

def iteritems(coll: Mapping[_K, _V]) -> Iterable[tuple[_K, _V]]: ...
def itervalues(coll: Mapping[Any, _V]) -> Iterable[_V]: ...

def join(colls: Iterable[_T]) -> _T | None: ...

@overload
def merge(__coll: _T, *colls: _T) -> _T: ...
@overload
def merge() -> None: ...

def join_with(f: Callable[[list[Any]], Any], dicts: Iterable[Mapping[_K, Any]], strict: bool = ...) -> dict[_K, Any]: ...
def merge_with(f: Callable[[list[Any]], Any], *dicts: Mapping[_K, Any]) -> dict[_K, Any]: ...

### Walk / Select

@overload
def walk(f: Callable[[_T], _V2], coll: list[_T]) -> list[_V2]: ...
@overload
def walk(f: Callable[[_T], _V2], coll: set[_T]) -> set[_V2]: ...
@overload
def walk(f: Callable[..., Any] | _Func, coll: dict[Any, Any]) -> dict[Any, Any]: ...
@overload
def walk(f: Callable[..., Any] | _Func, coll: _T) -> _T: ...

@overload
def walk_keys(f: Callable[[_K], _K2], coll: dict[_K, _V]) -> dict[_K2, _V]: ...
@overload
def walk_keys(f: None, coll: dict[_K, _V]) -> dict[_K, _V]: ...
@overload
def walk_keys(f: AbstractSet[Any], coll: dict[Any, _V]) -> dict[bool, _V]: ...
@overload
def walk_keys(f: str | bytes | re.Pattern[str], coll: dict[Any, _V]) -> dict[_ReResult | None, _V]: ...
@overload
def walk_keys(f: int, coll: dict[Sequence[_T], _V]) -> dict[_T, _V]: ...
@overload
def walk_keys(f: Mapping[_K, _K2], coll: dict[_K, _V]) -> dict[_K2, _V]: ...

@overload
def walk_values(f: Callable[[_V], _V2], coll: dict[_K, _V]) -> dict[_K, _V2]: ...
@overload
def walk_values(f: None, coll: dict[_K, _V]) -> dict[_K, _V]: ...
@overload
def walk_values(f: AbstractSet[Any], coll: dict[_K, Any]) -> dict[_K, bool]: ...
@overload
def walk_values(f: str | bytes | re.Pattern[str], coll: dict[_K, Any]) -> dict[_K, _ReResult | None]: ...
@overload
def walk_values(f: int, coll: dict[_K, Sequence[_V]]) -> dict[_K, _V]: ...
@overload
def walk_values(f: slice, coll: dict[_K, Sequence[_V]]) -> dict[_K, Sequence[_V]]: ...
@overload
def walk_values(f: Mapping[_V, _V2], coll: dict[_K, _V]) -> dict[_K, _V2]: ...

def select(pred: Callable[..., Any] | _Func, coll: _T) -> _T: ...
def select_keys(pred: Callable[[_K], Any] | _Func, coll: dict[_K, _V]) -> dict[_K, _V]: ...
def select_values(pred: Callable[[_V], Any] | _Func, coll: dict[_K, _V]) -> dict[_K, _V]: ...

def split_keys(pred: Callable[[_K], Any] | _Func, coll: Mapping[_K, _V]) -> tuple[dict[_K, _V], dict[_K, _V]]: ...

def compact(coll: _T) -> _T: ...

### Content tests

@overload
def is_distinct(coll: Any) -> bool: ...
@overload
def is_distinct(coll: Any, key: Callable[..., Any] | _Func) -> bool: ...

@overload
def all(seq: Iterable[Any]) -> bool: ...
@overload
def all(pred: Callable[..., Any] | _Func, seq: Iterable[Any]) -> bool: ...

@overload
def any(seq: Iterable[Any]) -> bool: ...
@overload
def any(pred: Callable[..., Any] | _Func, seq: Iterable[Any]) -> bool: ...

@overload
def none(seq: Iterable[Any]) -> bool: ...
@overload
def none(pred: Callable[..., Any] | _Func, seq: Iterable[Any]) -> bool: ...

@overload
def one(seq: Iterable[Any]) -> bool: ...
@overload
def one(pred: Callable[..., Any] | _Func, seq: Iterable[Any]) -> bool: ...

@overload
def some(seq: Iterable[_T]) -> _T | None: ...
@overload
def some(pred: Callable[..., Any] | _Func, seq: Iterable[_T]) -> _T | None: ...

### Dict utilities

def zipdict(keys: Iterable[_K], vals: Iterable[_V]) -> dict[_K, _V]: ...
def flip(mapping: dict[_K, _V]) -> dict[_V, _K]: ...
def project(mapping: dict[_K, _V], keys: Iterable[_K]) -> dict[_K, _V]: ...
def omit(mapping: dict[_K, _V], keys: Iterable[_K]) -> dict[_K, _V]: ...

def zip_values(*dicts: Mapping[_K, _V]) -> Iterator[tuple[_V, ...]]: ...
def zip_dicts(*dicts: Mapping[_K, _V]) -> Iterator[tuple[_K, tuple[_V, ...]]]: ...

### Nested access

def get_in(coll: Any, path: Iterable[Any], default: Any = ...) -> Any: ...
def get_lax(coll: Any, path: Iterable[Any], default: Any = ...) -> Any: ...
def set_in(coll: Any, path: Sequence[Any], value: Any) -> Any: ...
def update_in(coll: Any, path: Sequence[Any], update: Callable[[Any], Any], default: Any = ...) -> Any: ...
def del_in(coll: Any, path: Sequence[Any]) -> Any: ...
def has_path(coll: Any, path: Iterable[Any]) -> bool: ...

### Query

def where(mappings: Iterable[_T], **cond: Any) -> Iterator[_T]: ...
def pluck(key: Any, mappings: Iterable[Mapping[_K, _V]]) -> Iterator[_V]: ...
def pluck_attr(attr: str, objects: Iterable[Any]) -> Iterator[Any]: ...
def invoke(objects: Iterable[Any], name: str, *args: Any, **kwargs: Any) -> Iterator[Any]: ...

def lwhere(mappings: Iterable[_T], **cond: Any) -> list[_T]: ...
def lpluck(key: Any, mappings: Iterable[Mapping[_K, _V]]) -> list[_V]: ...
def lpluck_attr(attr: str, objects: Iterable[Any]) -> list[Any]: ...
def linvoke(objects: Iterable[Any], name: str, *args: Any, **kwargs: Any) -> list[Any]: ...
