from collections.abc import Callable, Iterable, Iterator
from typing import Any, TypeVar, overload

__all__ = [
    'tap',
    'log_calls', 'print_calls',
    'log_enters', 'print_enters',
    'log_exits', 'print_exits',
    'log_errors', 'print_errors',
    'log_durations', 'print_durations',
    'log_iter_durations', 'print_iter_durations',
]

_T = TypeVar('_T')
_F = TypeVar('_F', bound=Callable[..., Any])

def tap(x: _T, label: str | None = ...) -> _T: ...

### Logging decorators

def log_calls(print_func: Callable[..., Any], errors: bool = ..., stack: bool = ..., repr_len: int = ...) -> Callable[[_F], _F]: ...

@overload
def print_calls(func: _F) -> _F: ...
@overload
def print_calls(errors: bool = ..., stack: bool = ..., repr_len: int = ...) -> Callable[[_F], _F]: ...

def log_enters(print_func: Callable[..., Any], repr_len: int = ...) -> Callable[[_F], _F]: ...

@overload
def print_enters(func: _F) -> _F: ...
@overload
def print_enters(repr_len: int = ...) -> Callable[[_F], _F]: ...

def log_exits(print_func: Callable[..., Any], errors: bool = ..., stack: bool = ..., repr_len: int = ...) -> Callable[[_F], _F]: ...

@overload
def print_exits(func: _F) -> _F: ...
@overload
def print_exits(errors: bool = ..., stack: bool = ..., repr_len: int = ...) -> Callable[[_F], _F]: ...

### Error / Duration context managers + decorators

class log_errors:
    def __init__(self, print_func: Callable[..., Any], label: str | None = ..., stack: bool = ..., repr_len: int = ...) -> None: ...
    @overload
    def __call__(self, func: _F) -> _F: ...
    @overload
    def __call__(self, label: str | None = ..., **kwargs: Any) -> log_errors: ...
    def __enter__(self) -> log_errors: ...
    def __exit__(self, *exc: Any) -> None: ...

print_errors: log_errors

class log_durations:
    def __init__(self, print_func: Callable[..., Any], label: str | None = ..., unit: str = ..., threshold: float = ..., repr_len: int = ...) -> None: ...
    @overload
    def __call__(self, func: _F) -> _F: ...
    @overload
    def __call__(self, label: str | None = ..., **kwargs: Any) -> log_durations: ...
    def __enter__(self) -> log_durations: ...
    def __exit__(self, *exc: Any) -> None: ...

print_durations: log_durations

def log_iter_durations(seq: Iterable[_T], print_func: Callable[..., Any], label: str | None = ..., unit: str = ...) -> Iterator[_T]: ...
def print_iter_durations(seq: Iterable[_T], label: str | None = ..., unit: str = ...) -> Iterator[_T]: ...
