from collections.abc import Callable, Iterable, Iterator
from contextlib import suppress, AbstractContextManager
from datetime import timedelta
from typing import Any, NoReturn, ParamSpec, TypeVar, overload

__all__ = ['raiser', 'ignore', 'silent', 'suppress', 'nullcontext', 'reraise', 'retry', 'fallback',
           'limit_error_rate', 'ErrorRateExceeded', 'throttle',
           'post_processing', 'collecting', 'joining',
           'once', 'once_per', 'once_per_args',
           'wrap_with']

_T = TypeVar('_T')
_T2 = TypeVar('_T2')
_P = ParamSpec('_P')
_F = TypeVar('_F', bound=Callable[..., Any])

_ExcType = type[BaseException] | tuple[type[BaseException], ...]

### Error handling

def raiser(exception_or_class: BaseException | type[BaseException] | str = ..., *args: Any, **kwargs: Any) -> Callable[..., NoReturn]: ...

def ignore(errors: _ExcType | Iterable[type[BaseException]], default: Any = ...) -> Callable[[_F], _F]: ...
def silent(func: _F) -> _F: ...

from contextlib import nullcontext

def reraise(errors: _ExcType | Iterable[type[BaseException]], into: BaseException | type[BaseException] | Callable[[BaseException], BaseException]) -> AbstractContextManager[None]: ...

def retry(tries: int, errors: _ExcType | Iterable[type[BaseException]] = ..., timeout: int | float | Callable[[int], float] = ..., filter_errors: Callable[[BaseException], bool] | None = ...) -> Callable[[_F], _F]: ...

def fallback(*approaches: Callable[[], Any] | tuple[Callable[[], Any], _ExcType | Iterable[type[BaseException]]]) -> Any: ...

class ErrorRateExceeded(Exception): ...

def limit_error_rate(fails: int, timeout: int | float | timedelta, exception: type[BaseException] = ...) -> Callable[[_F], _F]: ...

def throttle(period: int | float | timedelta) -> Callable[[_F], _F]: ...

### Post processing

def post_processing(func: Callable[[_T], _T2]) -> Callable[[Callable[_P, _T]], Callable[_P, _T2]]: ...
def collecting(func: Callable[_P, Iterable[_T]]) -> Callable[_P, list[_T]]: ...
def joining(sep: str) -> Callable[[Callable[_P, Any]], Callable[_P, str]]: ...

### Initialization

def once_per(*argnames: str) -> Callable[[_F], _F]: ...
def once(func: _F) -> _F: ...
def once_per_args(func: _F) -> _F: ...

def wrap_with(ctx: Any) -> Callable[[_F], _F]: ...
