from _typeshed import Incomplete
from functools import partial as partial, reduce as reduce

__all__ = ['identity', 'constantly', 'caller', 'reduce', 'partial', 'rpartial', 'func_partial', 'curry', 'rcurry', 'autocurry', 'iffy', 'compose', 'rcompose', 'complement', 'juxt', 'ljuxt']

def identity(x): ...
def constantly(x): ...
def caller(*a, **kw): ...
def func_partial(func, *args, **kwargs): ...
def rpartial(func, *args, **kwargs): ...
def curry(func, n=...): ...
def rcurry(func, n=...): ...
def autocurry(func, n=..., _spec: Incomplete | None = None, _args=(), _kwargs={}): ...
def iffy(pred, action=..., default=...): ...
def compose(*fs): ...
def rcompose(*fs): ...
def complement(pred): ...
def ljuxt(*fs): ...
def juxt(*fs): ...
