import re
from collections.abc import Callable, Mapping, Set as AbstractSet
from typing import Any

__all__ = ['all_fn', 'any_fn', 'none_fn', 'one_fn', 'some_fn']

# All types accepted by the extended function protocol (funcmakers.make_func)
_XFunc = Callable[..., Any] | int | slice | str | bytes | re.Pattern[str] | Mapping[Any, Any] | AbstractSet[Any] | None

def all_fn(*fs: _XFunc) -> Callable[..., bool]: ...
def any_fn(*fs: _XFunc) -> Callable[..., bool]: ...
def none_fn(*fs: _XFunc) -> Callable[..., bool]: ...
def one_fn(*fs: _XFunc) -> Callable[..., bool]: ...
def some_fn(*fs: _XFunc) -> Callable[..., Any]: ...
