import re
from collections.abc import Callable, Iterator, Mapping, Set as AbstractSet
from functools import partial, reduce
from typing import Any, TypeVar, overload

__all__ = ['identity', 'constantly', 'caller',
           'reduce', 'partial',
           'rpartial', 'func_partial',
           'curry', 'rcurry', 'autocurry',
           'iffy',
           'compose', 'rcompose', 'complement', 'juxt', 'ljuxt']

_T = TypeVar('_T')
_T2 = TypeVar('_T2')
_F = TypeVar('_F', bound=Callable[..., Any])

# Non-callable types accepted by the extended function protocol (funcmakers.make_func)
_Func = int | slice | str | bytes | re.Pattern[str] | Mapping[Any, Any] | AbstractSet[Any] | None

def identity(x: _T) -> _T: ...
def constantly(x: _T) -> Callable[..., _T]: ...
def caller(*a: Any, **kw: Any) -> Callable[[Callable[..., _T]], _T]: ...

def func_partial(func: Callable[..., _T], *args: Any, **kwargs: Any) -> Callable[..., _T]: ...
def rpartial(func: Callable[..., _T], *args: Any, **kwargs: Any) -> Callable[..., _T]: ...

def curry(func: Callable[..., _T], n: int = ...) -> Callable[..., _T]: ...
def rcurry(func: Callable[..., _T], n: int = ...) -> Callable[..., _T]: ...
def autocurry(func: _F, n: int = ...) -> _F: ...

@overload
def iffy(action: Callable[..., _T]) -> Callable[..., _T]: ...
@overload
def iffy(pred: Any, action: Callable[..., _T], default: Any = ...) -> Callable[..., _T]: ...
@overload
def iffy(pred: Any, action: Any = ..., default: Any = ...) -> Callable[..., Any]: ...

@overload
def compose(__f: Callable[..., _T], *rest: Callable[..., Any] | _Func) -> Callable[..., _T]: ...
@overload
def compose(*fs: _Func) -> Callable[..., Any]: ...

@overload
def rcompose(__f: Callable[..., _T]) -> Callable[..., _T]: ...
@overload
def rcompose(__f1: Callable[..., Any] | _Func, __f2: Callable[..., _T]) -> Callable[..., _T]: ...
@overload
def rcompose(__f1: Callable[..., Any] | _Func, __f2: Callable[..., Any] | _Func, __f3: Callable[..., _T]) -> Callable[..., _T]: ...
@overload
def rcompose(*fs: Callable[..., Any] | _Func) -> Callable[..., Any]: ...

def complement(pred: Callable[..., Any] | _Func) -> Callable[..., bool]: ...

@overload
def juxt(__f1: Callable[..., _T], __f2: Callable[..., _T2]) -> Callable[..., Iterator[_T | _T2]]: ...
@overload
def juxt(*fs: Callable[..., Any] | _Func) -> Callable[..., Iterator[Any]]: ...

@overload
def ljuxt(__f1: Callable[..., _T], __f2: Callable[..., _T2]) -> Callable[..., list[_T | _T2]]: ...
@overload
def ljuxt(*fs: Callable[..., Any] | _Func) -> Callable[..., list[Any]]: ...
