import re
from collections.abc import Callable, Mapping, Set as AbstractSet
from typing import Any

__all__ = ['all_fn', 'any_fn', 'none_fn', 'one_fn', 'some_fn']

# Non-callable types accepted by the extended function protocol (funcmakers.make_func)
_Func = int | slice | str | bytes | re.Pattern[str] | Mapping[Any, Any] | AbstractSet[Any] | None

def all_fn(*fs: Callable[..., Any] | _Func) -> Callable[..., bool]: ...
def any_fn(*fs: Callable[..., Any] | _Func) -> Callable[..., bool]: ...
def none_fn(*fs: Callable[..., Any] | _Func) -> Callable[..., bool]: ...
def one_fn(*fs: Callable[..., Any] | _Func) -> Callable[..., bool]: ...
def some_fn(*fs: Callable[..., Any] | _Func) -> Callable[..., Any]: ...
