__all__ = ['isnone', 'notnone', 'inc', 'dec', 'even', 'odd']

def isnone(x: object) -> bool: ...
def notnone(x: object) -> bool: ...
def inc(x: int) -> int: ...
def dec(x: int) -> int: ...
def even(x: int) -> bool: ...
def odd(x: int) -> bool: ...
