import re
from collections.abc import Callable, Iterable, Iterator, Mapping, Set as AbstractSet, Sequence
from typing import Any, TypeAlias, TypeVar, overload
from itertools import chain, count, cycle, repeat, accumulate

__all__ = [
    'count', 'cycle', 'repeat', 'repeatedly', 'iterate',
    'take', 'drop', 'first', 'second', 'nth', 'last', 'rest', 'butlast', 'ilen',
    'map', 'filter', 'lmap', 'lfilter', 'remove', 'lremove', 'keep', 'lkeep', 'without', 'lwithout',
    'concat', 'lconcat', 'chain', 'cat', 'lcat', 'flatten', 'lflatten', 'mapcat', 'lmapcat',
    'interleave', 'interpose', 'distinct', 'ldistinct',
    'dropwhile', 'takewhile', 'split', 'lsplit', 'split_at', 'lsplit_at', 'split_by', 'lsplit_by',
    'group_by', 'group_by_keys', 'group_values', 'count_by', 'count_reps',
    'partition', 'lpartition', 'chunks', 'lchunks', 'partition_by', 'lpartition_by',
    'with_prev', 'with_next', 'pairwise', 'lzip',
    'reductions', 'lreductions', 'sums', 'lsums', 'accumulate',
]

_K = TypeVar('_K')
_T = TypeVar('_T')
_V = TypeVar('_V')

# Non-callable types accepted by the extended function protocol (funcmakers.make_func):
# int/slice for itemgetter, str/bytes/re.Pattern for regex,
# Mapping for lookup, Set for membership, None for identity/bool
_Func = int | slice | str | bytes | re.Pattern[str] | Mapping[Any, Any] | AbstractSet[Any] | None
_ReResult: TypeAlias = str | tuple[str, ...] | dict[str, str]

### Generators

def repeatedly(f: Callable[[], _T], n: int = ...) -> Iterator[_T]: ...
def iterate(f: Callable[[_T], _T], x: _T) -> Iterator[_T]: ...

### Slicing

def take(n: int, seq: Iterable[_T]) -> list[_T]: ...
def drop(n: int, seq: Iterable[_T]) -> Iterator[_T]: ...
def first(seq: Iterable[_T]) -> _T | None: ...
def second(seq: Iterable[_T]) -> _T | None: ...
def nth(n: int, seq: Iterable[_T]) -> _T | None: ...
def last(seq: Iterable[_T]) -> _T | None: ...
def rest(seq: Iterable[_T]) -> Iterator[_T]: ...
def butlast(seq: Iterable[_T]) -> Iterator[_T]: ...
def ilen(seq: Iterable[Any]) -> int: ...

### Map / Filter

@overload
def map(f: Callable[[_T], _V], seq: Iterable[_T]) -> Iterator[_V]: ...
@overload
def map(f: None, seq: Iterable[_T]) -> Iterator[_T]: ...
@overload
def map(f: AbstractSet[Any], seq: Iterable[Any]) -> Iterator[bool]: ...
@overload
def map(f: str | bytes | re.Pattern[str], seq: Iterable[Any]) -> Iterator[_ReResult | None]: ...
@overload
def map(f: int, seq: Iterable[Sequence[_T]]) -> Iterator[_T]: ...
@overload
def map(f: slice, seq: Iterable[Sequence[_T]]) -> Iterator[Sequence[_T]]: ...
@overload
def map(f: Mapping[_K, _V], seq: Iterable[_K]) -> Iterator[_V]: ...
@overload
def map(f: Callable[..., _V], *seqs: Iterable[Any]) -> Iterator[_V]: ...

@overload
def lmap(f: Callable[[_T], _V], seq: Iterable[_T]) -> list[_V]: ...
@overload
def lmap(f: None, seq: Iterable[_T]) -> list[_T]: ...
@overload
def lmap(f: AbstractSet[Any], seq: Iterable[Any]) -> list[bool]: ...
@overload
def lmap(f: str | bytes | re.Pattern[str], seq: Iterable[Any]) -> list[_ReResult | None]: ...
@overload
def lmap(f: int, seq: Iterable[Sequence[_T]]) -> list[_T]: ...
@overload
def lmap(f: slice, seq: Iterable[Sequence[_T]]) -> list[Sequence[_T]]: ...
@overload
def lmap(f: Mapping[_K, _V], seq: Iterable[_K]) -> list[_V]: ...
@overload
def lmap(f: Callable[..., _V], *seqs: Iterable[Any]) -> list[_V]: ...

def filter(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> Iterator[_T]: ...
def lfilter(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> list[_T]: ...

def remove(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> Iterator[_T]: ...
def lremove(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> list[_T]: ...

@overload
def keep(seq: Iterable[_T]) -> Iterator[_T]: ...
@overload
def keep(f: Callable[[_T], _V], seq: Iterable[_T]) -> Iterator[_V]: ...
@overload
def keep(f: None, seq: Iterable[_T]) -> Iterator[_T]: ...
@overload
def keep(f: AbstractSet[Any], seq: Iterable[Any]) -> Iterator[bool]: ...
@overload
def keep(f: str | bytes | re.Pattern[str], seq: Iterable[Any]) -> Iterator[_ReResult | None]: ...
@overload
def keep(f: int, seq: Iterable[Sequence[_T]]) -> Iterator[_T]: ...
@overload
def keep(f: slice, seq: Iterable[Sequence[_T]]) -> Iterator[Sequence[_T]]: ...
@overload
def keep(f: Mapping[_K, _V], seq: Iterable[_K]) -> Iterator[_V]: ...

@overload
def lkeep(seq: Iterable[_T]) -> list[_T]: ...
@overload
def lkeep(f: Callable[[_T], _V], seq: Iterable[_T]) -> list[_V]: ...
@overload
def lkeep(f: None, seq: Iterable[_T]) -> list[_T]: ...
@overload
def lkeep(f: AbstractSet[Any], seq: Iterable[Any]) -> list[bool]: ...
@overload
def lkeep(f: str | bytes | re.Pattern[str], seq: Iterable[Any]) -> list[_ReResult | None]: ...
@overload
def lkeep(f: int, seq: Iterable[Sequence[_T]]) -> list[_T]: ...
@overload
def lkeep(f: slice, seq: Iterable[Sequence[_T]]) -> list[Sequence[_T]]: ...
@overload
def lkeep(f: Mapping[_K, _V], seq: Iterable[_K]) -> list[_V]: ...

def without(seq: Iterable[_T], *items: _T) -> Iterator[_T]: ...
def lwithout(seq: Iterable[_T], *items: _T) -> list[_T]: ...

### Concat / Flatten

def concat(*seqs: Iterable[_T]) -> Iterator[_T]: ...
def lconcat(*seqs: Iterable[_T]) -> list[_T]: ...
def cat(seqs: Iterable[Iterable[_T]]) -> Iterator[_T]: ...
def lcat(seqs: Iterable[Iterable[_T]]) -> list[_T]: ...

def flatten(seq: Iterable[Any], follow: Callable[[Any], bool] = ...) -> Iterator[Any]: ...
def lflatten(seq: Iterable[Any], follow: Callable[[Any], bool] = ...) -> list[Any]: ...

@overload
def mapcat(f: Callable[[_T], Iterable[_V]], seq: Iterable[_T]) -> Iterator[_V]: ...
@overload
def mapcat(f: int, seq: Iterable[Sequence[Iterable[_T]]]) -> Iterator[_T]: ...
@overload
def mapcat(f: Mapping[_K, Iterable[_V]], seq: Iterable[_K]) -> Iterator[_V]: ...
@overload
def mapcat(f: Callable[..., Iterable[_V]], *seqs: Iterable[Any]) -> Iterator[_V]: ...
@overload
def mapcat(f: Callable[..., Any] | _Func, *seqs: Iterable[Any]) -> Iterator[Any]: ...

@overload
def lmapcat(f: Callable[[_T], Iterable[_V]], seq: Iterable[_T]) -> list[_V]: ...
@overload
def lmapcat(f: int, seq: Iterable[Sequence[Iterable[_T]]]) -> list[_T]: ...
@overload
def lmapcat(f: Mapping[_K, Iterable[_V]], seq: Iterable[_K]) -> list[_V]: ...
@overload
def lmapcat(f: Callable[..., Iterable[_V]], *seqs: Iterable[Any]) -> list[_V]: ...
@overload
def lmapcat(f: Callable[..., Any] | _Func, *seqs: Iterable[Any]) -> list[Any]: ...

def interleave(*seqs: Iterable[_T]) -> Iterator[_T]: ...
def interpose(sep: _T, seq: Iterable[_T]) -> Iterator[_T]: ...

### Distinct

def distinct(seq: Iterable[_T], key: Callable[[_T], Any] | _Func = ...) -> Iterator[_T]: ...
def ldistinct(seq: Iterable[_T], key: Callable[[_T], Any] | _Func = ...) -> list[_T]: ...

### Takewhile / Dropwhile / Split

@overload
def takewhile(seq: Iterable[_T]) -> Iterator[_T]: ...
@overload
def takewhile(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> Iterator[_T]: ...

@overload
def dropwhile(seq: Iterable[_T]) -> Iterator[_T]: ...
@overload
def dropwhile(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> Iterator[_T]: ...

def split(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> tuple[Iterator[_T], Iterator[_T]]: ...
def lsplit(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> tuple[list[_T], list[_T]]: ...

def split_at(n: int, seq: Iterable[_T]) -> tuple[Iterator[_T], Iterator[_T]]: ...
def lsplit_at(n: int, seq: Iterable[_T]) -> tuple[list[_T], list[_T]]: ...

def split_by(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> tuple[Iterator[_T], Iterator[_T]]: ...
def lsplit_by(pred: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> tuple[list[_T], list[_T]]: ...

### Grouping

@overload
def group_by(f: Callable[[_T], _K], seq: Iterable[_T]) -> dict[_K, list[_T]]: ...
@overload
def group_by(f: None, seq: Iterable[_T]) -> dict[_T, list[_T]]: ...
@overload
def group_by(f: AbstractSet[Any], seq: Iterable[_T]) -> dict[bool, list[_T]]: ...
@overload
def group_by(f: str | bytes | re.Pattern[str], seq: Iterable[_T]) -> dict[_ReResult | None, list[_T]]: ...
@overload
def group_by(f: int, seq: Iterable[Sequence[_T]]) -> dict[_T, list[Sequence[_T]]]: ...
@overload
def group_by(f: Mapping[_K, _V], seq: Iterable[_K]) -> dict[_V, list[_K]]: ...

@overload
def group_by_keys(get_keys: Callable[[_T], Iterable[_K]], seq: Iterable[_T]) -> dict[_K, list[_T]]: ...
@overload
def group_by_keys(get_keys: _Func, seq: Iterable[_T]) -> dict[Any, list[_T]]: ...

def group_values(seq: Iterable[tuple[_K, _V]]) -> dict[_K, list[_V]]: ...

@overload
def count_by(f: Callable[[_T], _K], seq: Iterable[_T]) -> dict[_K, int]: ...
@overload
def count_by(f: None, seq: Iterable[_T]) -> dict[_T, int]: ...
@overload
def count_by(f: AbstractSet[Any], seq: Iterable[Any]) -> dict[bool, int]: ...
@overload
def count_by(f: str | bytes | re.Pattern[str], seq: Iterable[Any]) -> dict[_ReResult | None, int]: ...
@overload
def count_by(f: int, seq: Iterable[Sequence[_T]]) -> dict[_T, int]: ...
@overload
def count_by(f: Mapping[_K, _V], seq: Iterable[_K]) -> dict[_V, int]: ...

def count_reps(seq: Iterable[_T]) -> dict[_T, int]: ...

### Partitioning

@overload
def partition(n: int, seq: Iterable[_T]) -> Iterator[list[_T]]: ...
@overload
def partition(n: int, step: int, seq: Iterable[_T]) -> Iterator[list[_T]]: ...

@overload
def lpartition(n: int, seq: Iterable[_T]) -> list[list[_T]]: ...
@overload
def lpartition(n: int, step: int, seq: Iterable[_T]) -> list[list[_T]]: ...

@overload
def chunks(n: int, seq: Iterable[_T]) -> Iterator[list[_T]]: ...
@overload
def chunks(n: int, step: int, seq: Iterable[_T]) -> Iterator[list[_T]]: ...

@overload
def lchunks(n: int, seq: Iterable[_T]) -> list[list[_T]]: ...
@overload
def lchunks(n: int, step: int, seq: Iterable[_T]) -> list[list[_T]]: ...

def partition_by(f: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> Iterator[Iterator[_T]]: ...
def lpartition_by(f: Callable[[_T], Any] | _Func, seq: Iterable[_T]) -> list[list[_T]]: ...

### Pairing

def with_prev(seq: Iterable[_T], fill: _T | None = ...) -> Iterator[tuple[_T, _T | None]]: ...
def with_next(seq: Iterable[_T], fill: _T | None = ...) -> Iterator[tuple[_T, _T | None]]: ...
def pairwise(seq: Iterable[_T]) -> Iterator[tuple[_T, _T]]: ...

def lzip(*seqs: Iterable[Any], strict: bool = ...) -> list[tuple[Any, ...]]: ...

### Reductions

@overload
def reductions(f: Callable[[_T, _T], _T], seq: Iterable[_T]) -> Iterator[_T]: ...
@overload
def reductions(f: Callable[[_T, _T], _T], seq: Iterable[_T], acc: _T) -> Iterator[_T]: ...

@overload
def lreductions(f: Callable[[_T, _T], _T], seq: Iterable[_T]) -> list[_T]: ...
@overload
def lreductions(f: Callable[[_T, _T], _T], seq: Iterable[_T], acc: _T) -> list[_T]: ...

def sums(seq: Iterable[_T], acc: _T = ...) -> Iterator[_T]: ...
def lsums(seq: Iterable[_T], acc: _T = ...) -> list[_T]: ...
