__all__ = ['re_iter', 're_all', 're_find', 're_finder', 're_test', 're_tester', 'str_join', 'cut_prefix', 'cut_suffix']

def re_iter(regex, s, flags: int = 0): ...
def re_all(regex, s, flags: int = 0): ...
def re_find(regex, s, flags: int = 0): ...
def re_test(regex, s, flags: int = 0): ...
def re_finder(regex, flags: int = 0): ...
def re_tester(regex, flags: int = 0): ...
def str_join(sep, seq=...): ...
def cut_prefix(s, prefix): ...
def cut_suffix(s, suffix): ...
