from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['tree_leaves', 'ltree_leaves', 'tree_nodes', 'ltree_nodes']

def tree_leaves(root, follow=..., children=...) -> Generator[Incomplete, None, None]: ...
def ltree_leaves(root, follow=..., children=...): ...
def tree_nodes(root, follow=..., children=...) -> Generator[Incomplete, None, None]: ...
def ltree_nodes(root, follow=..., children=...): ...
